minimumReleaseAge: 1440

updateConfig:
  ignoreDependencies:
    - '@titaniumnetwork-dev/ultraviolet'

allowBuilds:
  '@mercuryworkshop/scramjet': true
  bufferutil: true
  core-js: true
  esbuild: true
  utf-8-validate: true
